import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DotGrid from './components/DotGrid';
import Navbar from "./navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        {/* BACKGROUND: Fixed dan di belakang semua konten */}
        <DotGrid
          dotSize={10}
          gap={15}
          baseColor="#dadada"
          activeColor="#a1a1a1"
          proximity={120}
          shockRadius={250}
          shockStrength={5}
          resistance={750}
          returnDuration={1.5}
          className="fixed top-0 left-0 w-full h-full -z-50 pointer-events-none"
        />

        {/* KONTEN UTAMA */}
        <div className="relative z-0 min-h-full flex flex-col">
          <Navbar />
          <main className="flex-1">
          </main>
        </div>
      </body>
    </html>
  );
}