import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FloatingBlobsBackground from "./components/FloatingBlobsBackground";

import Navbar from "./navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative">
          <FloatingBlobsBackground />

          <div style={{
            position: 'relative',
            zIndex: 1,
            minHeight: '100vh',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
            padding: '2rem'
          }}>

            {/* Konten skills Anda di sini */}
            <div style={{ maxWidth: '800px', background: 'rgba(255, 255, 255, 0.9)', padding: '2rem', borderRadius: '12px' }}>
              {/* Tambahkan konten skills Anda */}
            </div>
          </div>
        </div>
        <Navbar />
        <main className=""> {/* <--- TAMBAHKAN INI */}
          {children}
        </main>
      </body>
    </html>
  );
}
