import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DotGrid from './components/DotGrid';

import Navbar from "./navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* BACKGROUND: Diletakkan di sini, di lapisan paling bawah */}
        <div className="w-full h-screen relative">
          <DotGrid
            dotSize={10}
            gap={15}
            baseColor="#dadada" // Warna sedikit lebih netral untuk background
            activeColor="#a1a1a1"
            proximity={120}
            shockRadius={250}
            shockStrength={5}
            resistance={750}
            returnDuration={1.5}
            className="fixed top-0 left-0 -z-10 pointer-events-none" // <-- Kunci utamanya di sini
          />
        </div>

        {/* KONTEN UTAMA: Diletakkan di atas background */}
        <Navbar />

        <main className="relative z-0"> 
          {/* z-0 membuat main tetap di atas background (-z-10) */}
          {children}
        </main>
      </body>
    </html>
  );
}
